config/routes.rb
Rails.application.routes.draw do
 root :to => 'homes#top'
 resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id]) #@book = Book.findは'一つの'レコードを取り出す動作
    if @book.update(book_params) #取り出したレコードを編集してデータベースに保存し直す
      flash[:success] = "Book was successfully updated."
      redirect_to book_path(@book.id) #show（今回取り出したレコード）ページに飛ばす
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @book = Book.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<html>
  <head></head>
  <body>
   <h1>Editing Book</h1>
   <%= form_with model: @book do |f| %>
     <def>
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this book from being saved:
         <ul>
           <% @book.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
         </ul>
       <% end %>
       <h4>Title</h4>
       <%= f.text_field :title %>
     </def>
     <def>
       <h4>Body</h4>
       <%= f.text_area :body %>
     </def>
     <def>
       <%= f.submit 'Update Book' %>
     </def>
   <% end %>
   <%= link_to "Show", book_path(@book.id), method: :get %>
   <%= link_to "Back", books_path %>
  </body>
</html>

app/views/books/index.html.erb
<html>
  <head></head>
  <body>
    <p id="notice"></p>
    <h1>Books</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", book_path(book.id) %></td>
          <td><%= link_to "Edit", edit_book_path(book.id) %></td>
          <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？"%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <h2>New book</h2>
    <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_with model: @book do |f| %>
      <div>
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div>
        <h4>Body</h4>
        <%= f.text_area :body %>
      </div>
      <div>
        <%= f.submit 'Create Book' %>
      </div>
    <% end %>
  </body>
</html>

app/views/books/show.html.erb
<html>
  <head></head>
  <body>
    <p id="notice"></p>
    <p>
      <strong>Title</strong>
      <%= @book.title %>
    </p>
    <p>
      <strong>Body</strong>
      <%= @book.body %>
    </p>
    <%= link_to "Edit", edit_book_path(@book.id) %>
    <%= link_to "Back", books_path %>
  </body>
</html>

app/views/homes/top.html.erb
<html>
  <head></head>
  <body>
    <h1>ようこそ Bookers へ！</h1>
    <p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <p><%= link_to "start",books_path(@book.id),method: :get %></p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:success] %>
    <%= yield %>
  </body>
</html>